version: '3.1'

services:
  web:
    container_name: webappcdp
    restart : always
    build: .
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: cdp
    ports:
      - 3001:3306
    volumes:
      - ./data:/data/db

  adminer:
    container_name: adminersql
    image: adminer
    restart: always
    ports:
      - 8081:8080